config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  get "/dashboard" => "accounts#index"
  get "profile/:username" => "accounts#profile", as: :profile
  get "post/like/:post_id" => "likes#save_like", as: :like_post
  post "follow/account" => "accounts#follow_account", as: :follow_account

  resources :posts
  
  root to: "public#homepage"
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #profile image

  has_many :posts
  has_many :likes

  def full_name
    "#{first_name} #{last_name}"
  end

  def total_followers
    Follower.where(follower_id: self.id).count
  end

  def total_following
    Follower.where(following_id: self.id).count
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follower.rb
class Follower < ApplicationRecord
    validates_uniqueness_of :follower_id, :scope => [:following_id]
end

app/models/like.rb
class Like < ApplicationRecord

end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/post.rb
class Post < ApplicationRecord
    default_scope { order created_at: :desc }
    belongs_to :account

    has_many :likes

    before_create :set_active
    scope :active, -> {where active: true }


    def total_likes
        0
    end

    private


    def set_active
        self.active= true
    end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
    before_action :authenticate_account!
    before_action :set_account, only: [:profile]

    def index

        followers_ids = Follower.where(follower_id: current_account.id).map(&:following_id)
        followers_ids << current_account.id

        @posts = Post.includes(:account).where(account_id: followers_ids).active

        following_ids = Follower.where(follower_id: current_account.id).map(&:following_id)
        following_ids << current_account.id

        @follower_suggestions = Account.where.not(id: following_ids)
    end

    def profile
        @posts = @account.posts.active
    end

    def follow_account
        follower_id = params[:follow_id]
        if Follower.create!(follower_id: current_account.id, following_id: follower_id)
            flash[:success] = "Now following user"
        else
            flash[:danger] = "Unable to follow user"
        end
        redirect_to dashboard_path

    end

    private

    def set_account
        @account = Account.find_by_username(params[:username])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :first_name, :last_name, :description])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :first_name, :last_name, :email, :password])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

    before_action :authenticate_account!

    def save_like
        @like = Like.new(post_id: params[:post_id], account_id: current_account.id)
        @post_id = params[:post_id]
        respond_to do |format|
            format.js{
                if @like.save
                    @success = true
                else
                    @success = false
                end
                render "posts/like"
            }
        end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_account!
    
    def new
        @post = Post.new
    end

    def create
        @post = Post.new(post_prams)
        @post.account_id = current_account.id if account_signed_in?

        if @post.save
            redirect_to dashboard_path, flash: { success: "Mumble successful!"}
        else
            redirect_to new_post__path, flash: { danger: "Mumble unsuccessful :("}
    
        end
    end

    
    def show
    end


    private

    def post_prams
        params.require(:post).permit(:post)
    end

end

app/controllers/public_controller.rb
class PublicController < ApplicationController
    def homepage
        
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
    def profile_picture account, width = 100
        image_path = account.image.present? ? account.image.thumb.url : "dp.png"
        image_tag(image_path, width: width, class: "img-circle")
    end

    def can_edit_profile? profile_id
        account_signed_in? && current_account.id == profile_id
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/accounts/_follower_suggestions.html.erb
<% @follower_suggestions.each do |account| %>
    <div class="recommended-follower">
        <div class="row">
            <div class="col-sm-3 col-lg-2">
                <%= link_to profile_picture(account, 40), profile_path(account.username)%>
            </div>
            <div class="col-sm-9 col-lg-10">
            <%= form_tag follow_account_path, method: :post, class: "float-right" do %>
                <%= hidden_field_tag :follow_id, account.id %>
                <%= submit_tag "Follow", class: "btn btn-info btn-sm"%>
            <% end %>
            <strong><%= link_to account.username, profile_path(account.username), class:"text-dark" %></strong>
            <p style="color: #575151;font-size: 10pt"><%= account.created_at > 2.days.ago ? "New to Mumblr" : "Followed by X users" %></p>
            </div>
        </div>
    </div>
<%end%>

app/views/accounts/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-8">
            <% @posts.each do |post| %>
                <div class="post-style">
                    <div class="post-meta">
                        <%= link_to post.account.username, profile_path(post.account.username), class:"text-dark" %>
                    </div>

                    <div class="actual-post">

                        <%= post.post %>
                    </div>
                    <div class="post-bottom">
                        <i class="fa fa-heart like-<%= post.id %> post-like" data-id="<%=post.id%>"></i>
                        <i class="fa fa-comment post-comment"></i>
                        <strong ><%= post.total_likes %> likes</strong>
                        <p class="text-muted"><%= time_ago_in_words post.created_at %> ago</p>
                    </div>
                </div>
            <% end %>
        </div>
        <div class="col-4">
                <div class="account-summary">
                    <p><strong><%= current_account.username %></strong><br />
                    <span style="color: #666666;"><%= current_account.full_name %></span></p>
                </div>
                <div class="follower-suggestions">
                    <%= link_to "View All", "#", class:"float-right text-dark"%>
                    <p class="text-muted">Suggestions for you</p>
                    <%= render "accounts/follower_suggestions"%>
                </div>
        </div>
    </div>
</div>

app/views/accounts/profile.html.erb
<div class="contaner">
    <div class="row">
        <div class="col-4">
            <img style="position:absolute; TOP:-10px; LEFT:90px;" src="https://i.ibb.co/gRT7Lh9/dp.png" alt="dp" border="0">
        </div>
        <div class="col-8 text-left">
            <h1><%= @account.full_name %></h1>
            <%= link_to "Edit Profile", edit_account_registration_path, class: "btn btn-secondary" if can_edit_profile?(@account.id) %> 
            <div class="profile-stats"><%= @account.posts.count %> mumbles</div>
            <div class="profile-stats"><%= @account.total_followers %> followers</div>
            <div class="profile-stats"><%= @account.total_following%> following</div>
            </br>
            <%= simple_format @account.description %>
        </div>
    </div>
    <div class="row profile-posts">
        <% @posts.each do |post| %>
            <div class="col-4">
                <div class="post-style">
                    <div class="actual-post">
                        <%= post.post %>
                    </div>
                    <div class="post-bottom">
                        <i class="fa fa-heart like-<%= post.id %> post-like" data-id="<%=post.id%>"></i>
                        <i class="fa fa-comment post-comment"></i>
                        <strong ><%= post.total_likes %> likes</strong>
                        <p class="text-muted"><%= time_ago_in_words post.created_at %> ago</p>
                    </div>

                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/layouts/_account_nav.html.erb
<li class="nav-item active">
    <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
</li>
<li class="nav-item">
    <%= link_to "Mumble It", new_post_path, class: "nav-link" %>
</li>
<li class="nav-item">
    <%= link_to "My Profile", profile_path(current_account.username), class: "nav-link" %>
</li>
<li class="nav-item">
    <%= link_to "Sign Out", destroy_account_session_path, method: :delete, class: "nav-link" %>
</li>

app/views/layouts/_public_nav.html.erb
<li class="nav-item active">
<a class="nav-link" href="#">Home
  <span class="sr-only">(current)</span>
</a>
</li>
<li class="nav-item">
<a class="nav-link" href="#">About</a>
</li>
<li class="nav-item">
<a class="nav-link" href="#">Services</a>
</li>
<li class="nav-item">
<a class="nav-link" href="#">Contact</a>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>MUMBLR</title>

  <!-- Bootstrap core CSS -->
  <%= stylesheet_link_tag "application", :media => "all" %>

  <title>MUMBLR</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

</head>

<body>
  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
    <div class="container">
      <a class="navbar-brand" href="#">MUMBLR</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
        <% if account_signed_in? %>
          <%= render "layouts/account_nav" %>
        <% else %>
          <%= render "layouts/public_nav" %>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <%= yield %>
      </div>
    </div>
  </div>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
    <div class="field">
      <div class="control">
        <%= f.text_area :post,:cols => "40", :rows => "6", label: "Mumble", input_html: { class: "textarea "}, wrapper: false, label_html: {class: "label"}, placeholder: "Compose a new mumble...", autofocus: true %>
      </div>
    </div>
    <%= f.button :submit, class: "button is-info" %>

<% end %>

app/views/posts/like.js.erb
$(".like-<%= @post_id %>").addClass("active");

app/views/posts/new.html.erb
<h2>New Mumble</h2>

<%= render "form" %>